### ISSUE TITLE
Map initializes in null island

### ISSUE THREAD

**Issue by fenimore** [zebesta/NYC-Cycle-Map#1]
Hey cool app! I'm just now checking it out, and I see that it starts on null island, maybe there's a way to set the map to NY coordinates?

**Comment by zebesta** [comment]
Hmm thats strange, both a clean build from source and the downloaded app from the google play store are both opening above NYC for me.
![screenshot_2016-09-23-13-25-24](https://cloud.githubusercontent.com/assets/16945299/18795265/b879af00-8191-11e6-9dd3-e3c593d09df4.png)
From NewMap in the onMapReady function:

```
if (mSavedCameraPosition != null) {
            mMap.moveCamera(CameraUpdateFactory.newCameraPosition(mSavedCameraPosition));
        } else {
            mMap.moveCamera(CameraUpdateFactory.newLatLngZoom(new LatLng(40.7119042, -74.0066549), 8));
        }
```

**Comment by fenimore** [comment]
Yeah sorry I don't know what happened :S, the first time I installed it it went to 0,0 - but I tried again, even emptying the cache, and starts right were it should :), nevermind!
