### ISSUE TITLE
Refresh map on screen rotation

### ISSUE THREAD

**Issue by fenimore** [zebesta/NYC-Cycle-Map#2]
So I've noticed the map refreshes, posting the data points on screen rotations. I'm not sure if this'll work for your app, I'm unable to build because I don't have the keys, but one could add:

> android:configChanges="keyboardHidden|orientation|screenSize"

in the manifest under the main activity, this way the screen would rotate but the map wouldn't "Mapping 1000 data points" each time. At least, I think that would happen if you added the aforementioned line to the manifest.

**Comment by zebesta** [comment]
This does work, thanks for the input!
